/*
 * THIS FILE IS GENERATED BY scripts/promote.sh
 *
 * DO NOT MODIFY
 *
 * This file is used to dynamically update the content 
 * shown on the main site, including the home page and any 
 * content loaded from documentation/, contribute/, and wiki/.
 *
 * To see which pages from the main site are using this replacement:
 
    grep -ricE '[^!]\${xwalk-[^-]+-[^-]+-[^-]+}' * | grep -v '0$'
   
 *
 * Script injection occurs in xwalk.js replace_version_string
 *
 * The following pattern is replaced:
 *
 * ${XWALK-<CHANNEL>-<PLATFORM>-<ARCH>}
 *
 * To prevent replacement (eg., for a wiki page documenting
 * this process, prefix the ${XWALK...} with an exclamation (!)
 *
 * For example:
 *
 *   crosswalk-${XWALK-BETA-ANDROID-X86}.zip 
 *   crosswalk-!${XWALK-BETA-ANDROID-X86}.zip 
 *
 * would result in:
 *
 *   crosswalk-2.31.27.0.zip
 *   crosswalk-${XWALK-BETA-ANDROID-X86}.zip 
 *
 * See './site.sh promote' for a script to update this file
 * and push it to the website without pushing an entirely new
 * website (eg., without needing to run './site.sh mklive').
 *
 */
var versions = {
    stable: {
        android: {
            x86: "1.29.4.7", 
            arm: "0.0.0.0"
        },
        tizen: {
            x86: "1.29.4.7", 
            arm: "0.0.0.0"
        },
    },
    beta: {
        android: {
            x86: "2.31.27.0", 
            arm: "0.0.0.0"
        },
        tizen: {
            x86: "2.31.27.0", 
            arm: "0.0.0.0"
        },
    }
};